export interface EasePlacesFeature {
  id: string;
  name: string;
  category: "Arts, Culture & Enrichment" | "Recreation / Leisure & Open Spaces" | "Shopping" | "Food & Dining";
  type: string;
  airConditioned: boolean;
  freeEntry: boolean;
  address: string;
  operatingHours: string;
  reviewSource?: string;
  reviewNote?: string;
  lat: number;
  lng: number;
}

export const EASE_PLACES_DATA: EasePlacesFeature[] = [
  {
    id: "cp-1",
    name: "ACMI",
    category: "Arts, Culture & Enrichment",
    type: "Cinema",
    airConditioned: true,
    freeEntry: false,
    address: "Federation Square, Melbourne VIC 3000",
    operatingHours: "Mon-Sun 10:00 am - 5:00 pm",
    lat: -37.818,
    lng: 144.969,
  },
  {
    id: "cp-2",
    name: "Melbourne Museum",
    category: "Arts, Culture & Enrichment",
    type: "Museum",
    airConditioned: true,
    freeEntry: false,
    address: "11 Nicholson St, Carlton VIC 3053",
    operatingHours: "Mon-Sun 10:00 am - 5:00 pm",
    lat: -37.803,
    lng: 144.9716,
  },
  {
    id: "cp-3",
    name: "State Library Victoria",
    category: "Arts, Culture & Enrichment",
    type: "Library",
    airConditioned: true,
    freeEntry: true,
    address: "328 Swanston St, Melbourne VIC 3000",
    operatingHours: "Mon-Thu 10:00 am - 9:00 pm | Fri-Sun 10:00 am - 6:00 pm",
    lat: -37.81,
    lng: 144.9647,
  },
  {
    id: "cp-4",
    name: "Birrarung Marr",
    category: "Recreation / Leisure & Open Spaces",
    type: "Park",
    airConditioned: false,
    freeEntry: true,
    address: "Batman Ave, Melbourne VIC 3000",
    operatingHours: "Open 24 hours",
    lat: -37.8195,
    lng: 144.9738,
  },
  {
    id: "cp-4b",
    name: "Treasury Gardens",
    category: "Recreation / Leisure & Open Spaces",
    type: "Garden",
    airConditioned: false,
    freeEntry: true,
    address: "2-18 Wellington Parade, East Melbourne VIC 3002",
    operatingHours: "Open 24 hours",
    lat: -37.8148,
    lng: 144.9756,
  },
  {
    id: "cp-5",
    name: "Royal Botanic Gardens",
    category: "Recreation / Leisure & Open Spaces",
    type: "Botanical Garden",
    airConditioned: false,
    freeEntry: true,
    address: "Birdwood Ave, South Yarra VIC 3141",
    operatingHours: "Mon-Sun 7:30 am - Sunset",
    lat: -37.8304,
    lng: 144.9796,
  },
  {
    id: "cp-5b",
    name: "Fitzroy Gardens",
    category: "Recreation / Leisure & Open Spaces",
    type: "Garden",
    airConditioned: false,
    freeEntry: true,
    address: "230-298 Wellington Parade, East Melbourne VIC 3002",
    operatingHours: "Open 24 hours",
    lat: -37.8136,
    lng: 144.9799,
  },
  {
    id: "cp-6",
    name: "Melbourne Central",
    category: "Shopping",
    type: "Shopping Centre",
    airConditioned: true,
    freeEntry: true,
    address: "211 La Trobe St, Melbourne VIC 3000",
    operatingHours: "Mon-Thu 10:00 am - 7:00 pm | Fri 10:00 am - 9:00 pm | Sat-Sun 10:00 am - 6:00 pm",
    lat: -37.8102,
    lng: 144.9629,
  },
  {
    id: "cp-7",
    name: "National Gallery of Victoria",
    category: "Arts, Culture & Enrichment",
    type: "Gallery",
    airConditioned: true,
    freeEntry: true,
    address: "180 St Kilda Rd, Melbourne VIC 3006",
    operatingHours: "Mon-Sun 10:00 am - 5:00 pm",
    lat: -37.8226,
    lng: 144.9689,
  },
  {
    id: "cp-8",
    name: "Immigration Museum",
    category: "Arts, Culture & Enrichment",
    type: "Museum",
    airConditioned: true,
    freeEntry: false,
    address: "400 Flinders St, Melbourne VIC 3000",
    operatingHours: "Mon-Sun 10:00 am - 5:00 pm",
    lat: -37.8193,
    lng: 144.9605,
  },
  {
    id: "cp-9",
    name: "The Ian Potter Centre",
    category: "Arts, Culture & Enrichment",
    type: "Gallery",
    airConditioned: true,
    freeEntry: true,
    address: "Fed Square, Melbourne VIC 3000",
    operatingHours: "Mon-Sun 10:00 am - 5:00 pm",
    lat: -37.8177,
    lng: 144.9691,
  },
  {
    id: "cp-10",
    name: "Queen Victoria Market",
    category: "Shopping",
    type: "Market",
    airConditioned: false,
    freeEntry: true,
    address: "Queen St, Melbourne VIC 3000",
    operatingHours: "Tue-Thu 6:00 am - 3:00 pm | Fri 6:00 am - 5:00 pm | Sat-Sun 6:00 am - 4:00 pm",
    lat: -37.8076,
    lng: 144.9568,
  },
  {
    id: "cp-11",
    name: "Emporium Melbourne",
    category: "Shopping",
    type: "Shopping Centre",
    airConditioned: true,
    freeEntry: true,
    address: "287 Lonsdale St, Melbourne VIC 3000",
    operatingHours: "Mon-Thu 10:00 am - 7:00 pm | Fri 10:00 am - 9:00 pm | Sat-Sun 10:00 am - 7:00 pm",
    lat: -37.8110,
    lng: 144.9647,
  },
  {
    id: "cp-12",
    name: "DFO South Wharf",
    category: "Shopping",
    type: "Outlet Centre",
    airConditioned: true,
    freeEntry: true,
    address: "20 Convention Centre Pl, South Wharf VIC 3006",
    operatingHours: "Mon-Sun 10:00 am - 6:00 pm",
    lat: -37.8241,
    lng: 144.9515,
  },
  {
    id: "cp-13",
    name: "Carlton Gardens",
    category: "Recreation / Leisure & Open Spaces",
    type: "Garden",
    airConditioned: false,
    freeEntry: true,
    address: "1-111 Carlton St, Carlton VIC 3053",
    operatingHours: "Open 24 hours",
    lat: -37.8066,
    lng: 144.9713,
  },
  {
    id: "cp-14",
    name: "Southbank Promenade",
    category: "Recreation / Leisure & Open Spaces",
    type: "Promenade",
    airConditioned: false,
    freeEntry: true,
    address: "Southbank VIC 3006",
    operatingHours: "Open 24 hours",
    lat: -37.8208,
    lng: 144.9644,
  },
  {
    id: "cp-15",
    name: "Arts Centre Melbourne",
    category: "Arts, Culture & Enrichment",
    type: "Performing Arts Centre",
    airConditioned: true,
    freeEntry: false,
    address: "100 St Kilda Rd, Melbourne VIC 3004",
    operatingHours: "Hours vary by event",
    lat: -37.8211,
    lng: 144.9674,
  },
  {
    id: "cp-16",
    name: "Melbourne Recital Centre",
    category: "Arts, Culture & Enrichment",
    type: "Performance Venue",
    airConditioned: true,
    freeEntry: false,
    address: "31 Sturt St, Southbank VIC 3006",
    operatingHours: "Hours vary by event",
    lat: -37.8235,
    lng: 144.9671,
  },
  {
    id: "cp-17",
    name: "Library at The Dock",
    category: "Arts, Culture & Enrichment",
    type: "Library",
    airConditioned: true,
    freeEntry: true,
    address: "107 Victoria Harbour Promenade, Docklands VIC 3008",
    operatingHours: "Daily 10:00 am - 6:00 pm",
    lat: -37.8142,
    lng: 144.9472,
  },
  {
    id: "cp-18",
    name: "QV Melbourne",
    category: "Shopping",
    type: "Shopping Centre",
    airConditioned: true,
    freeEntry: true,
    address: "Cnr Swanston St & Lonsdale St, Melbourne VIC 3000",
    operatingHours: "Daily 10:00 am - 7:00 pm",
    lat: -37.8106,
    lng: 144.9651,
  },
  {
    id: "cp-19",
    name: "South Melbourne Market",
    category: "Shopping",
    type: "Market",
    airConditioned: false,
    freeEntry: true,
    address: "322-326 Coventry St, South Melbourne VIC 3205",
    operatingHours: "Wed, Fri-Sun trading days; hours vary by stall",
    lat: -37.8321,
    lng: 144.9565,
  },
  {
    id: "cp-20",
    name: "Flagstaff Gardens",
    category: "Recreation / Leisure & Open Spaces",
    type: "Garden",
    airConditioned: false,
    freeEntry: true,
    address: "309-311 William St, West Melbourne VIC 3003",
    operatingHours: "Open 24 hours",
    lat: -37.8107,
    lng: 144.9543,
  },
  {
    id: "cp-21",
    name: "Alexandra Gardens",
    category: "Recreation / Leisure & Open Spaces",
    type: "Garden",
    airConditioned: false,
    freeEntry: true,
    address: "3 Boathouse Dr, Melbourne VIC 3004",
    operatingHours: "Open 24 hours",
    lat: -37.8206,
    lng: 144.9712,
  },
  {
    id: "cp-22",
    name: "Gimlet at Cavendish House",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "33 Russell St, Melbourne VIC 3000",
    operatingHours: "Mon-Thu 12:00 pm - 12:00 am | Fri-Sat 12:00 pm - 1:00 am | Sun 12:00 pm - 12:00 am",
    reviewSource: "Broadsheet + What's On Melbourne",
    reviewNote: "Recognised among standout CBD dining rooms for polished service and city occasion dining.",
    lat: -37.816,
    lng: 144.9693,
  },
  {
    id: "cp-23",
    name: "Grill Americano",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "112 Flinders Ln, Melbourne VIC 3000",
    operatingHours: "Open from 12:00 pm daily",
    reviewSource: "Broadsheet + What's On Melbourne",
    reviewNote: "A highly rated CBD grill known for Italian brasserie energy and wood-fired signatures.",
    lat: -37.8169,
    lng: 144.9702,
  },
  {
    id: "cp-24",
    name: "MoVida",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "1 Hosier Ln, Melbourne VIC 3000",
    operatingHours: "Mon-Thu 12:00 pm - 10:00 pm | Fri-Sat 12:00 pm - 10:30 pm | Sun 12:00 pm - 10:00 pm",
    reviewSource: "Broadsheet + What's On Melbourne",
    reviewNote: "A long-running Melbourne favourite for contemporary Spanish tapas in the CBD core.",
    lat: -37.8168,
    lng: 144.969,
  },
  {
    id: "cp-25",
    name: "Victoria by Farmer's Daughters",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "Federation Square, Swanston St & Flinders St, Melbourne VIC 3000",
    operatingHours: "Thu-Sat 5:30 pm - late | Sun 11:30 am - 5:00 pm",
    reviewSource: "Broadsheet",
    reviewNote: "Highlighted for showcasing Victorian produce in a prominent Fed Square dining setting.",
    lat: -37.8179,
    lng: 144.9681,
  },
  {
    id: "cp-26",
    name: "Embla",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "122 Russell St, Melbourne VIC 3000",
    operatingHours: "Mon-Sat 12:00 pm - 12:00 am | Sun closed",
    reviewSource: "What's On Melbourne",
    reviewNote: "Known for polished European wine-bar dining and a produce-driven wood-fire menu.",
    lat: -37.8156,
    lng: 144.9698,
  },
  {
    id: "cp-27",
    name: "Chin Chin",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "125 Flinders Ln, Melbourne VIC 3000",
    operatingHours: "Daily 11:00 am - 11:00 pm",
    reviewSource: "What's On Melbourne",
    reviewNote: "A flagship Flinders Lane favourite for energetic Thai-inspired share dining.",
    lat: -37.8168,
    lng: 144.9704,
  },
  {
    id: "cp-28",
    name: "Supernormal",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "180 Flinders Lane, Melbourne VIC 3000",
    operatingHours: "Mon-Thu 12:00 pm - 11:00 pm | Fri-Sat 12:00 pm - 12:00 am | Sun 12:00 pm - 11:00 pm",
    reviewSource: "What's On Melbourne",
    reviewNote: "Widely recognised for refined Asian-inspired dining and one of the lane's signature restaurant rooms.",
    lat: -37.8166,
    lng: 144.9721,
  },
  {
    id: "cp-29",
    name: "Cumulus Inc",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "45 Flinders Lane, Melbourne VIC 3000",
    operatingHours: "Daily 12:00 pm - 10:00 pm",
    reviewSource: "What's On Melbourne",
    reviewNote: "An award-winning Flinders Lane institution with all-day appeal and strong local produce focus.",
    lat: -37.8148,
    lng: 144.971,
  },
  {
    id: "cp-30",
    name: "Hazel",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "164 Flinders Ln, Melbourne VIC 3000",
    operatingHours: "Tue 5:30 pm - 10:00 pm | Wed-Sat 12:00 pm - 3:00 pm and 5:30 pm - 10:00 pm | Sun-Mon closed",
    reviewSource: "What's On Melbourne",
    reviewNote: "Praised for house-made charcuterie, wood-fire cooking, and a strong small-producer philosophy.",
    lat: -37.8166,
    lng: 144.9715,
  },
  {
    id: "cp-31",
    name: "Florentino",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "80 Bourke St, Melbourne VIC 3000",
    operatingHours: "Mon-Fri 12:00 pm - 11:00 pm | Sat 6:00 pm - 11:00 pm | Sun closed",
    reviewSource: "What's On Melbourne",
    reviewNote: "A long-running Melbourne icon for celebratory Italian dining in the Bourke Hill precinct.",
    lat: -37.8122,
    lng: 144.9729,
  },
  {
    id: "cp-32",
    name: "Tipo 00",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "361 Little Bourke St, Melbourne VIC 3000",
    operatingHours: "Mon-Sat 11:30 am - 10:00 pm | Sun closed",
    reviewSource: "What's On Melbourne",
    reviewNote: "Frequently highlighted for artisan house-made pasta and one of the city's most reliable Italian stops.",
    lat: -37.8132,
    lng: 144.9602,
  },
  {
    id: "cp-33",
    name: "Tonka",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "20 Duckboard Pl, Melbourne VIC 3000",
    operatingHours: "Mon-Thu 12:00 pm - 3:00 pm and 5:30 pm - 10:00 pm | Fri 12:00 pm - 10:00 pm | Sat 12:00 pm - 10:30 pm | Sun 12:00 pm - 9:00 pm",
    reviewSource: "What's On Melbourne",
    reviewNote: "A well-known laneway destination for modern Indian flavours with a fine-dining finish.",
    lat: -37.8178,
    lng: 144.9665,
  },
  {
    id: "cp-34",
    name: "Farmer's Daughters",
    category: "Food & Dining",
    type: "Restaurant recommendation",
    airConditioned: true,
    freeEntry: false,
    address: "6/80 Collins St, Melbourne VIC 3000",
    operatingHours: "Daily 11:30 am - 12:00 am",
    reviewSource: "Broadsheet + What's On Melbourne",
    reviewNote: "Recognised for showcasing Gippsland produce across a multi-level CBD venue.",
    lat: -37.8134,
    lng: 144.9738,
  },
];

export function easePlacesMarkerColor(category: string): { core: string; halo: string } {
  if (category.includes("Arts")) return { core: "#6a5ca5", halo: "rgba(106,92,165,0.22)" };
  if (category.includes("Recreation")) return { core: "#1f9d68", halo: "rgba(31,157,104,0.22)" };
  if (category.includes("Food") || category.includes("Dining")) return { core: "#dd6b20", halo: "rgba(221,107,32,0.22)" };
  return { core: "#d975a4", halo: "rgba(217,117,164,0.22)" };
}
