export interface EasePlacesFeature {
  id: string;
  name: string;
  category: "Arts, Culture & Enrichment" | "Recreation / Leisure & Open Spaces" | "Shopping";
  type: string;
  airConditioned: boolean;
  freeEntry: boolean;
  address: string;
  operatingHours: string;
  lat: number;
  lng: number;
}

export const EASE_PLACES_DATA: EasePlacesFeature[] = [
  {
    id: "cp-1",
    name: "ACMI",
    category: "Arts, Culture & Enrichment",
    type: "Cinema",
    airConditioned: true,
    freeEntry: false,
    address: "Federation Square, Melbourne VIC 3000",
    operatingHours: "Mon-Sun 10:00 am - 5:00 pm",
    lat: -37.818,
    lng: 144.969,
  },
  {
    id: "cp-2",
    name: "Melbourne Museum",
    category: "Arts, Culture & Enrichment",
    type: "Museum",
    airConditioned: true,
    freeEntry: false,
    address: "11 Nicholson St, Carlton VIC 3053",
    operatingHours: "Mon-Sun 10:00 am - 5:00 pm",
    lat: -37.803,
    lng: 144.9716,
  },
  {
    id: "cp-3",
    name: "State Library Victoria",
    category: "Arts, Culture & Enrichment",
    type: "Library",
    airConditioned: true,
    freeEntry: true,
    address: "328 Swanston St, Melbourne VIC 3000",
    operatingHours: "Mon-Thu 10:00 am - 9:00 pm | Fri-Sun 10:00 am - 6:00 pm",
    lat: -37.81,
    lng: 144.9647,
  },
  {
    id: "cp-4",
    name: "Birrarung Marr",
    category: "Recreation / Leisure & Open Spaces",
    type: "Park",
    airConditioned: false,
    freeEntry: true,
    address: "Batman Ave, Melbourne VIC 3000",
    operatingHours: "Open 24 hours",
    lat: -37.8195,
    lng: 144.9738,
  },
  {
    id: "cp-4b",
    name: "Treasury Gardens",
    category: "Recreation / Leisure & Open Spaces",
    type: "Garden",
    airConditioned: false,
    freeEntry: true,
    address: "2-18 Wellington Parade, East Melbourne VIC 3002",
    operatingHours: "Open 24 hours",
    lat: -37.8148,
    lng: 144.9756,
  },
  {
    id: "cp-5",
    name: "Royal Botanic Gardens",
    category: "Recreation / Leisure & Open Spaces",
    type: "Botanical Garden",
    airConditioned: false,
    freeEntry: true,
    address: "Birdwood Ave, South Yarra VIC 3141",
    operatingHours: "Mon-Sun 7:30 am - Sunset",
    lat: -37.8304,
    lng: 144.9796,
  },
  {
    id: "cp-5b",
    name: "Fitzroy Gardens",
    category: "Recreation / Leisure & Open Spaces",
    type: "Garden",
    airConditioned: false,
    freeEntry: true,
    address: "230-298 Wellington Parade, East Melbourne VIC 3002",
    operatingHours: "Open 24 hours",
    lat: -37.8136,
    lng: 144.9799,
  },
  {
    id: "cp-6",
    name: "Melbourne Central",
    category: "Shopping",
    type: "Shopping Centre",
    airConditioned: true,
    freeEntry: true,
    address: "211 La Trobe St, Melbourne VIC 3000",
    operatingHours: "Mon-Thu 10:00 am - 7:00 pm | Fri 10:00 am - 9:00 pm | Sat-Sun 10:00 am - 6:00 pm",
    lat: -37.8102,
    lng: 144.9629,
  },
  {
    id: "cp-7",
    name: "National Gallery of Victoria",
    category: "Arts, Culture & Enrichment",
    type: "Gallery",
    airConditioned: true,
    freeEntry: true,
    address: "180 St Kilda Rd, Melbourne VIC 3006",
    operatingHours: "Mon-Sun 10:00 am - 5:00 pm",
    lat: -37.8226,
    lng: 144.9689,
  },
  {
    id: "cp-8",
    name: "Immigration Museum",
    category: "Arts, Culture & Enrichment",
    type: "Museum",
    airConditioned: true,
    freeEntry: false,
    address: "400 Flinders St, Melbourne VIC 3000",
    operatingHours: "Mon-Sun 10:00 am - 5:00 pm",
    lat: -37.8193,
    lng: 144.9605,
  },
  {
    id: "cp-9",
    name: "The Ian Potter Centre",
    category: "Arts, Culture & Enrichment",
    type: "Gallery",
    airConditioned: true,
    freeEntry: true,
    address: "Fed Square, Melbourne VIC 3000",
    operatingHours: "Mon-Sun 10:00 am - 5:00 pm",
    lat: -37.8177,
    lng: 144.9691,
  },
  {
    id: "cp-10",
    name: "Queen Victoria Market",
    category: "Shopping",
    type: "Market",
    airConditioned: false,
    freeEntry: true,
    address: "Queen St, Melbourne VIC 3000",
    operatingHours: "Tue-Thu 6:00 am - 3:00 pm | Fri 6:00 am - 5:00 pm | Sat-Sun 6:00 am - 4:00 pm",
    lat: -37.8076,
    lng: 144.9568,
  },
  {
    id: "cp-11",
    name: "Emporium Melbourne",
    category: "Shopping",
    type: "Shopping Centre",
    airConditioned: true,
    freeEntry: true,
    address: "287 Lonsdale St, Melbourne VIC 3000",
    operatingHours: "Mon-Thu 10:00 am - 7:00 pm | Fri 10:00 am - 9:00 pm | Sat-Sun 10:00 am - 7:00 pm",
    lat: -37.8110,
    lng: 144.9647,
  },
  {
    id: "cp-12",
    name: "DFO South Wharf",
    category: "Shopping",
    type: "Outlet Centre",
    airConditioned: true,
    freeEntry: true,
    address: "20 Convention Centre Pl, South Wharf VIC 3006",
    operatingHours: "Mon-Sun 10:00 am - 6:00 pm",
    lat: -37.8241,
    lng: 144.9515,
  },
  {
    id: "cp-13",
    name: "Carlton Gardens",
    category: "Recreation / Leisure & Open Spaces",
    type: "Garden",
    airConditioned: false,
    freeEntry: true,
    address: "1-111 Carlton St, Carlton VIC 3053",
    operatingHours: "Open 24 hours",
    lat: -37.8066,
    lng: 144.9713,
  },
  {
    id: "cp-14",
    name: "Southbank Promenade",
    category: "Recreation / Leisure & Open Spaces",
    type: "Promenade",
    airConditioned: false,
    freeEntry: true,
    address: "Southbank VIC 3006",
    operatingHours: "Open 24 hours",
    lat: -37.8208,
    lng: 144.9644,
  },
  {
    id: "cp-15",
    name: "Arts Centre Melbourne",
    category: "Arts, Culture & Enrichment",
    type: "Performing Arts Centre",
    airConditioned: true,
    freeEntry: false,
    address: "100 St Kilda Rd, Melbourne VIC 3004",
    operatingHours: "Hours vary by event",
    lat: -37.8211,
    lng: 144.9674,
  },
  {
    id: "cp-16",
    name: "Melbourne Recital Centre",
    category: "Arts, Culture & Enrichment",
    type: "Performance Venue",
    airConditioned: true,
    freeEntry: false,
    address: "31 Sturt St, Southbank VIC 3006",
    operatingHours: "Hours vary by event",
    lat: -37.8235,
    lng: 144.9671,
  },
  {
    id: "cp-17",
    name: "Library at The Dock",
    category: "Arts, Culture & Enrichment",
    type: "Library",
    airConditioned: true,
    freeEntry: true,
    address: "107 Victoria Harbour Promenade, Docklands VIC 3008",
    operatingHours: "Daily 10:00 am - 6:00 pm",
    lat: -37.8142,
    lng: 144.9472,
  },
  {
    id: "cp-18",
    name: "QV Melbourne",
    category: "Shopping",
    type: "Shopping Centre",
    airConditioned: true,
    freeEntry: true,
    address: "Cnr Swanston St & Lonsdale St, Melbourne VIC 3000",
    operatingHours: "Daily 10:00 am - 7:00 pm",
    lat: -37.8106,
    lng: 144.9651,
  },
  {
    id: "cp-19",
    name: "South Melbourne Market",
    category: "Shopping",
    type: "Market",
    airConditioned: false,
    freeEntry: true,
    address: "322-326 Coventry St, South Melbourne VIC 3205",
    operatingHours: "Wed, Fri-Sun trading days; hours vary by stall",
    lat: -37.8321,
    lng: 144.9565,
  },
  {
    id: "cp-20",
    name: "Flagstaff Gardens",
    category: "Recreation / Leisure & Open Spaces",
    type: "Garden",
    airConditioned: false,
    freeEntry: true,
    address: "309-311 William St, West Melbourne VIC 3003",
    operatingHours: "Open 24 hours",
    lat: -37.8107,
    lng: 144.9543,
  },
  {
    id: "cp-21",
    name: "Alexandra Gardens",
    category: "Recreation / Leisure & Open Spaces",
    type: "Garden",
    airConditioned: false,
    freeEntry: true,
    address: "3 Boathouse Dr, Melbourne VIC 3004",
    operatingHours: "Open 24 hours",
    lat: -37.8206,
    lng: 144.9712,
  },
];

export function easePlacesMarkerColor(category: string): { core: string; halo: string } {
  if (category.includes("Arts")) return { core: "#6a5ca5", halo: "rgba(106,92,165,0.22)" };
  if (category.includes("Recreation")) return { core: "#1f9d68", halo: "rgba(31,157,104,0.22)" };
  return { core: "#d975a4", halo: "rgba(217,117,164,0.22)" };
}
